#!/usr/bin/env bash
# blue-green-switch.sh — atomic blue/green traffic switch.
#
# Faz 16 #174 — Operator tool for switching live traffic between the
# blue and green copies of api/gateway/console/portal.
#
# Usage:
#   infra/scripts/blue-green-switch.sh <blue|green> [--dry-run]
#
# The script:
#   1. Verifies the target color is healthy (all pods respond 200 to /healthz)
#   2. Rewrites infra/compose/bluegreen/active-color.conf atomically
#   3. SIGHUPs nginx to reload the config (no container restart)
#   4. Runs post-switch smoke test
#   5. Appends an audit log line to /var/log/personel/bluegreen.log
#
# Safety:
#   - Refuses to switch to an unhealthy color
#   - Refuses to switch during an active DSR fulfilment lifecycle
#     (checks /v1/dsr/active via API)
#   - Requires an interactive confirmation token when --force is absent

set -euo pipefail

TARGET="${1:-}"
DRY_RUN="${DRY_RUN:-false}"
FORCE="${FORCE:-false}"

if [ "$TARGET" != "blue" ] && [ "$TARGET" != "green" ]; then
  echo "Usage: $0 <blue|green> [--dry-run]" >&2
  exit 2
fi

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --force)   FORCE=true ;;
  esac
done

COMPOSE_DIR="${COMPOSE_DIR:-infra/compose}"
BG_DIR="${COMPOSE_DIR}/bluegreen"
ACTIVE_FILE="${BG_DIR}/active-color.conf"
LOG_FILE="${LOG_FILE:-/var/log/personel/bluegreen.log}"

# --- Helpers ---

log() {
  local msg="$*"
  echo "[blue-green] $msg"
  if [ -w "$(dirname "$LOG_FILE")" ] 2>/dev/null; then
    printf '%s\t%s\t%s\n' "$(date -Iseconds)" "${SUDO_USER:-$USER}" "$msg" >> "$LOG_FILE"
  fi
}

health_check_color() {
  local color="$1"
  local api_port gateway_port console_port portal_port

  case "$color" in
    blue)
      api_port=8000;  gateway_port=9443;  console_port=3000;  portal_port=3001
      ;;
    green)
      api_port=18001; gateway_port=19443; console_port=13000; portal_port=13001
      ;;
  esac

  log "health-check ${color}: api=${api_port} gateway=${gateway_port} console=${console_port} portal=${portal_port}"

  if ! curl -sfk "http://127.0.0.1:${api_port}/healthz" >/dev/null; then
    log "FAIL: ${color} api unhealthy"
    return 1
  fi
  if ! curl -sfk "http://127.0.0.1:${console_port}/healthz" >/dev/null; then
    log "FAIL: ${color} console unhealthy"
    return 1
  fi
  if ! curl -sfk "http://127.0.0.1:${portal_port}/healthz" >/dev/null; then
    log "FAIL: ${color} portal unhealthy"
    return 1
  fi
  log "${color} healthy"
  return 0
}

check_dsr_inflight() {
  # Safety gate: a DSR fulfilment in the SLA-critical window must not
  # be interrupted by a switch. Queries the current blue's API.
  local inflight
  if ! inflight=$(curl -sf http://127.0.0.1:8000/v1/dsr/active 2>/dev/null | jq -r '.count // 0'); then
    log "warn: DSR inflight check failed — proceeding"
    return 0
  fi
  if [ "$inflight" -gt 0 ] && [ "$FORCE" != "true" ]; then
    log "BLOCKED: $inflight active DSR(s); use --force to override"
    exit 1
  fi
}

confirm() {
  if [ "$FORCE" = "true" ]; then
    return 0
  fi
  read -rp "[blue-green] Type 'SWITCH ${TARGET}' to confirm: " token
  if [ "$token" != "SWITCH ${TARGET}" ]; then
    log "aborted — confirmation token mismatch"
    exit 1
  fi
}

rewrite_active() {
  local color="$1"
  mkdir -p "$BG_DIR"
  cat > "${ACTIVE_FILE}.new" <<EOF
# Auto-generated by blue-green-switch.sh at $(date -Iseconds)
# Active color: ${color}
upstream personel_api      { server personel-api-${color}:8000; }
upstream personel_gateway  { server personel-gateway-${color}:9443; }
upstream personel_console  { server personel-console-${color}:3000; }
upstream personel_portal   { server personel-portal-${color}:3001; }
EOF
  mv -f "${ACTIVE_FILE}.new" "$ACTIVE_FILE"
  log "rewrote ${ACTIVE_FILE} → ${color}"
}

reload_nginx() {
  if docker ps --format '{{.Names}}' | grep -q '^personel-bluegreen-router$'; then
    docker kill --signal HUP personel-bluegreen-router
    log "nginx reloaded"
  else
    log "warn: bluegreen-router container not running"
  fi
}

post_switch_smoke() {
  sleep 1
  if ! curl -sfk "https://127.0.0.1/healthz" >/dev/null; then
    log "ERROR: post-switch smoke failed — traffic is broken, consider reverting"
    exit 3
  fi
  log "post-switch smoke ok"
}

# --- Main ---

log "begin switch → ${TARGET} (dry-run=${DRY_RUN}, force=${FORCE})"

check_dsr_inflight

if ! health_check_color "$TARGET"; then
  log "ABORT: target ${TARGET} not healthy"
  exit 1
fi

if [ "$DRY_RUN" = "true" ]; then
  log "dry-run: skipping write + reload"
  exit 0
fi

confirm
rewrite_active "$TARGET"
reload_nginx
post_switch_smoke
log "done — active color is now ${TARGET}"
